# Generated by Django 4.0.4 on 2022-05-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp', '0002_prueba_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
